name: al4ea
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.6
  - tensorflow-gpu==1.15
  - pytorch==1.4.0
  - torchvision==0.5.0
  - torchaudio
  - pip
  - pip:
      - tqdm==4.56.0
      - scikit-learn==0.23.2
      - pandas==0.24.2
      - matching==0.1.1
      - numpy
      - scipy
      - matplotlib
      - networkx
